### ISSUE TITLE
Fix default button on Login Screen and in Chat

### ISSUE THREAD

**Issue by manuelmeyer1** [Trivadis/AzureDeveloperBootcamp#2]
When filling in my credentials I want to hit "Enter" and login. And not have to switch to the mouse!
When chatting I want to send my text with "Enter"!

Please fix this immediately. 

SO KANN ICH NICH AAAARBEITEN!!!!!!

**Comment by mkftrivadis** [comment]
Furthermore, it might help to set the focus to the first field by default.
